#ifndef __TUNE_H__
#define __TUNE_H__

#include "player.h"

const byte SongData0[] PROGMEM = {
  VOLUME, 0xA,
  INC_OCTAVE,
  NOTE_C, NOTE_E, NOTE_G, NOTE_B, NOTE_C, NOTE_E, NOTE_G, NOTE_B,
  NOTE_C, NOTE_E, NOTE_G, NOTE_AS, NOTE_C, NOTE_E, NOTE_G, NOTE_AS,
  NOTE_C, NOTE_E, NOTE_G, NOTE_B, NOTE_C, NOTE_E, NOTE_G, NOTE_B,
  NOTE_C, NOTE_E, NOTE_G, NOTE_AS, NOTE_C, NOTE_E, NOTE_G, NOTE_AS,
  END
};
const byte SongData1[] PROGMEM = {
  VOLUME, 4,
  REST|WITH_LEN|WITH_Q, 8, 8,
  INC_OCTAVE,
  NOTE_C, NOTE_E, NOTE_G, NOTE_B, NOTE_C, NOTE_E, NOTE_G, NOTE_B,
  NOTE_C, NOTE_E, NOTE_G, NOTE_AS, NOTE_C, NOTE_E, NOTE_G, NOTE_AS,
  NOTE_C, NOTE_E, NOTE_G, NOTE_B, NOTE_C, NOTE_E, NOTE_G, NOTE_B,
  NOTE_C, NOTE_E, NOTE_G, NOTE_AS, NOTE_C, NOTE_E, NOTE_G, NOTE_AS,
  END
};
const byte SongData2[] PROGMEM = {
  OCTAVE, 3,
  NOTE_C, NOTE_C, NOTE_C, NOTE_C, NOTE_C, NOTE_C, NOTE_C, NOTE_C,
  DEC_OCTAVE,
  NOTE_B, NOTE_B, NOTE_B, NOTE_B, NOTE_B, NOTE_B, NOTE_B, NOTE_B,

  INC_OCTAVE,
  NOTE_C, NOTE_C, NOTE_C, NOTE_C, NOTE_C, NOTE_C, NOTE_C, NOTE_C,
  DEC_OCTAVE,
  NOTE_B, NOTE_B, NOTE_B, NOTE_B, NOTE_B, NOTE_B, NOTE_B, NOTE_B,

  END
};
const byte SongData3[] PROGMEM = { END };

const byte* SongData[] = { SongData0, SongData1, SongData2, SongData3 };

#endif /* ifndef __TUNE_H__ */
